<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKFmEBia\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKFmEBia/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKFmEBia.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKFmEBia\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKFmEBia\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KFmEBia',
    'container.build_id' => '118b6fa0',
    'container.build_time' => 1576921725,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKFmEBia');
