<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'admin_index' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin/']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'livre_ajout' => [[], ['_controller' => 'App\\Controller\\LivreController::ajout'], [], [['text', '/livre/ajout']], [], []],
    'livre_editer' => [['id'], ['_controller' => 'App\\Controller\\LivreController::editer'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/livre/editer']], [], []],
    'livre_liste' => [[], ['_controller' => 'App\\Controller\\LivreController::liste'], [], [['text', '/livre/liste']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\AuteurController::liste'], [], [['text', '/']], [], []],
    'home_json' => [[], ['_controller' => 'App\\Controller\\HomeController::homeJson'], [], [['text', '/json']], [], []],
    'home_dynamic' => [[], ['_controller' => 'App\\Controller\\HomeController::homeDynamic'], [], [['text', '/dynamic']], [], []],
    'auteur_ajout' => [[], ['_controller' => 'App\\Controller\\AuteurController::ajout'], [], [['text', '/auteur/ajout']], [], []],
    'auteur_ajout_form' => [[], ['_controller' => 'App\\Controller\\AuteurController::ajoutAvecForm'], [], [['text', '/auteur/ajout-form']], [], []],
    'auteur_liste' => [[], ['_controller' => 'App\\Controller\\AuteurController::liste'], [], [['text', '/auteur/liste']], [], []],
    'auteur_editer' => [['id'], ['_controller' => 'App\\Controller\\AuteurController::editer'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/auteur/editer']], [], []],
    'auteur_supprimer' => [['id'], ['_controller' => 'App\\Controller\\AuteurController::supprimer'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/auteur/supprimer']], [], []],
    'auteur_service' => [[], ['_controller' => 'App\\Controller\\AuteurController::utilisationService'], [], [['text', '/auteur/service']], [], []],
    'acces_granted' => [[], ['_controller' => 'App\\Controller\\AdminController::accesAvecRole'], [], [['text', '/is-granted']], [], []],
];
